name: Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Release type (major / minor / patch)'
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version:
        - "3.10"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env-${{ github.run_number }}-${{ matrix.python-version }}
        auto-update-conda: true
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda env list
        python -m pip install --upgrade pip
        pip install rdkit-pypi
        conda install -y -c conda-forge openbabel
        conda install -y -c conda-forge xtb
        conda install -y -c conda-forge crest
        # conda install pytorch torchvision torchaudio cpuonly -c pytorch
        pip install torchani
        pip install .
        pip install pytest
        pip install pytest-cov
    - name: Run pytest
      shell: bash -el {0}
      run: |
        conda env list
        python -m pytest -v --cov=aqme --cov-report=xml